Application has thrown an uncaught exception and is terminated:
AssertionError: abnormal phantomjs exit code: 1
    at Console.assert (console.js:102:23)
    at ChildProcess.<anonymous> (C:\Users\mbooth4\Documents\My Web Sites\Shopping Buddies\node_modules\scraperjs\node_modules\phantom\phantom.js:153:28)
    at ChildProcess.emit (events.js:98:17)
    at Process.ChildProcess._handle.onexit (child_process.js:820:12)
